# Generated by Django 6.0.1 on 2026-02-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatch',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_practical',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='avg_leaves_per_month',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='max_lectures_per_week',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='is_fixed',
        ),
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentbatch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='preferred_end_slot',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='teacher',
            name='preferred_start_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generatedtimetable',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='size',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(max_length=3),
        ),
    ]
