# Generated by Django 6.0.3 on 2026-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_department_id_alter_generatedtimetable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='admin_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='slot_index',
            field=models.IntegerField(help_text='0-7 corresponding to time slots, or -1 for full day'),
        ),
    ]
